/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGVIDEOFIELDCONTAINEREDITORFIELDS_H_
#define _OSGVIDEOFIELDCONTAINEREDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribFieldContainerEditorDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class VideoFieldContainerEditor;

OSG_GEN_CONTAINERPTR(VideoFieldContainerEditor);

/*! \ingroup GrpContribFieldContainerEditorFieldTraits
    \ingroup GrpLibOSGContribFieldContainerEditor
 */
template <>
struct FieldTraits<VideoFieldContainerEditor *> :
    public FieldTraitsFCPtrBase<VideoFieldContainerEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<VideoFieldContainerEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBFIELDCONTAINEREDITOR_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFVideoFieldContainerEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFVideoFieldContainerEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakVideoFieldContainerEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<VideoFieldContainerEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdVideoFieldContainerEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<VideoFieldContainerEditor *,
                      RecordedRefCountPolicy  > SFRecVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<VideoFieldContainerEditor *,
                      UnrecordedRefCountPolicy> SFUnrecVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<VideoFieldContainerEditor *,
                      WeakRefCountPolicy      > SFWeakVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<VideoFieldContainerEditor *,
                      NoRefCountPolicy        > SFUncountedVideoFieldContainerEditorPtr;


/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<VideoFieldContainerEditor *,
                      RecordedRefCountPolicy  > MFRecVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<VideoFieldContainerEditor *,
                      UnrecordedRefCountPolicy> MFUnrecVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<VideoFieldContainerEditor *,
                      WeakRefCountPolicy      > MFWeakVideoFieldContainerEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<VideoFieldContainerEditor *,
                      NoRefCountPolicy        > MFUncountedVideoFieldContainerEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFRecVideoFieldContainerEditorPtr : 
    public PointerSField<VideoFieldContainerEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUnrecVideoFieldContainerEditorPtr : 
    public PointerSField<VideoFieldContainerEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFWeakVideoFieldContainerEditorPtr :
    public PointerSField<VideoFieldContainerEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUncountedVideoFieldContainerEditorPtr :
    public PointerSField<VideoFieldContainerEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFRecVideoFieldContainerEditorPtr :
    public PointerMField<VideoFieldContainerEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUnrecVideoFieldContainerEditorPtr :
    public PointerMField<VideoFieldContainerEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFWeakVideoFieldContainerEditorPtr :
    public PointerMField<VideoFieldContainerEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUncountedVideoFieldContainerEditorPtr :
    public PointerMField<VideoFieldContainerEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGVIDEOFIELDCONTAINEREDITORFIELDS_H_ */
