/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTFIELDEDITORFIELDS_H_
#define _OSGTEXTFIELDEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribFieldContainerEditorDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TextFieldEditor;

OSG_GEN_CONTAINERPTR(TextFieldEditor);

/*! \ingroup GrpContribFieldContainerEditorFieldTraits
    \ingroup GrpLibOSGContribFieldContainerEditor
 */
template <>
struct FieldTraits<TextFieldEditor *> :
    public FieldTraitsFCPtrBase<TextFieldEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TextFieldEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBFIELDCONTAINEREDITOR_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTextFieldEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTextFieldEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextFieldEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextFieldEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<TextFieldEditor *,
                      RecordedRefCountPolicy  > SFRecTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<TextFieldEditor *,
                      UnrecordedRefCountPolicy> SFUnrecTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<TextFieldEditor *,
                      WeakRefCountPolicy      > SFWeakTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldSFields */
typedef PointerSField<TextFieldEditor *,
                      NoRefCountPolicy        > SFUncountedTextFieldEditorPtr;


/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<TextFieldEditor *,
                      RecordedRefCountPolicy  > MFRecTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<TextFieldEditor *,
                      UnrecordedRefCountPolicy> MFUnrecTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<TextFieldEditor *,
                      WeakRefCountPolicy      > MFWeakTextFieldEditorPtr;
/*! \ingroup GrpContribFieldContainerEditorFieldMFields */
typedef PointerMField<TextFieldEditor *,
                      NoRefCountPolicy        > MFUncountedTextFieldEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFRecTextFieldEditorPtr : 
    public PointerSField<TextFieldEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUnrecTextFieldEditorPtr : 
    public PointerSField<TextFieldEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFWeakTextFieldEditorPtr :
    public PointerSField<TextFieldEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldSFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct SFUncountedTextFieldEditorPtr :
    public PointerSField<TextFieldEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFRecTextFieldEditorPtr :
    public PointerMField<TextFieldEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUnrecTextFieldEditorPtr :
    public PointerMField<TextFieldEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFWeakTextFieldEditorPtr :
    public PointerMField<TextFieldEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribFieldContainerEditorFieldMFields \ingroup GrpLibOSGContribFieldContainerEditor */
struct MFUncountedTextFieldEditorPtr :
    public PointerMField<TextFieldEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTFIELDEDITORFIELDS_H_ */
