/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TextFieldEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"




#include "OSGTextFieldEditorBase.h"
#include "OSGTextFieldEditor.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TextFieldEditor
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<TextFieldEditor *>::_type("TextFieldEditorPtr", "SingleFieldEditorComponentPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(TextFieldEditor *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TextFieldEditor *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TextFieldEditor *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TextFieldEditorBase::classDescInserter(TypeObject &oType)
{
}


TextFieldEditorBase::TypeObject TextFieldEditorBase::_type(
    TextFieldEditorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&TextFieldEditorBase::createEmptyLocal),
    TextFieldEditor::initMethod,
    TextFieldEditor::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TextFieldEditor::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TextFieldEditor\"\n"
    "    parent=\"SingleFieldEditorComponent\"\n"
    "    library=\"ContribFieldContainerEditor\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TextFieldEditorBase::getType(void)
{
    return _type;
}

const FieldContainerType &TextFieldEditorBase::getType(void) const
{
    return _type;
}

UInt32 TextFieldEditorBase::getContainerSize(void) const
{
    return sizeof(TextFieldEditor);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 TextFieldEditorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TextFieldEditorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TextFieldEditorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TextFieldEditorTransitPtr TextFieldEditorBase::createLocal(BitVector bFlags)
{
    TextFieldEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TextFieldEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TextFieldEditorTransitPtr TextFieldEditorBase::createDependent(BitVector bFlags)
{
    TextFieldEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TextFieldEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TextFieldEditorTransitPtr TextFieldEditorBase::create(void)
{
    TextFieldEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TextFieldEditor>(tmpPtr);
    }

    return fc;
}

TextFieldEditor *TextFieldEditorBase::createEmptyLocal(BitVector bFlags)
{
    TextFieldEditor *returnValue;

    newPtr<TextFieldEditor>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TextFieldEditor *TextFieldEditorBase::createEmpty(void)
{
    TextFieldEditor *returnValue;

    newPtr<TextFieldEditor>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr TextFieldEditorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TextFieldEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextFieldEditor *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextFieldEditorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TextFieldEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextFieldEditor *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextFieldEditorBase::shallowCopy(void) const
{
    TextFieldEditor *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TextFieldEditor *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TextFieldEditorBase::TextFieldEditorBase(void) :
    Inherited()
{
}

TextFieldEditorBase::TextFieldEditorBase(const TextFieldEditorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TextFieldEditorBase::~TextFieldEditorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void TextFieldEditorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TextFieldEditor *pThis = static_cast<TextFieldEditor *>(this);

    pThis->execSync(static_cast<TextFieldEditor *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TextFieldEditorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TextFieldEditor *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TextFieldEditor *>(pRefAspect),
                  dynamic_cast<const TextFieldEditor *>(this));

    return returnValue;
}
#endif

void TextFieldEditorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
