/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PostShaderStage!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"


#include "OSGGLEXT.h"                     // ColorBufferFormat default header


#include "OSGPostShaderStageBase.h"
#include "OSGPostShaderStage.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PostShaderStage
    A stage that uses a shader in a post-process.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var GLenum          PostShaderStageBase::_sfColorBufferFormat
    
*/

/*! \var bool            PostShaderStageBase::_sfUseColorTextureBuffer
    Use a texture buffer with the frame buffer object so that the 
    color buffer is available as a texture in the shader.
*/

/*! \var bool            PostShaderStageBase::_sfUseDepthTextureBuffer
    Use a texture buffer with the frame buffer object so that the 
    depth buffer is available as a texture in the shader.
*/

/*! \var std::string     PostShaderStageBase::_sfVertexShader
    The shader code to use for the vertex program of the post-process.
*/

/*! \var std::string     PostShaderStageBase::_sfFragmentShader
    The shader code to use for the post-process.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<PostShaderStage *>::_type("PostShaderStagePtr", "StagePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(PostShaderStage *)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PostShaderStageBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFGLenum::Description(
        SFGLenum::getClassType(),
        "ColorBufferFormat",
        "",
        ColorBufferFormatFieldId, ColorBufferFormatFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&PostShaderStage::editHandleColorBufferFormat),
        static_cast<FieldGetMethodSig >(&PostShaderStage::getHandleColorBufferFormat));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "UseColorTextureBuffer",
        "Use a texture buffer with the frame buffer object so that the \n"
        "color buffer is available as a texture in the shader.\n",
        UseColorTextureBufferFieldId, UseColorTextureBufferFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&PostShaderStage::editHandleUseColorTextureBuffer),
        static_cast<FieldGetMethodSig >(&PostShaderStage::getHandleUseColorTextureBuffer));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "UseDepthTextureBuffer",
        "Use a texture buffer with the frame buffer object so that the \n"
        "depth buffer is available as a texture in the shader.\n",
        UseDepthTextureBufferFieldId, UseDepthTextureBufferFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&PostShaderStage::editHandleUseDepthTextureBuffer),
        static_cast<FieldGetMethodSig >(&PostShaderStage::getHandleUseDepthTextureBuffer));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "VertexShader",
        "The shader code to use for the vertex program of the post-process.\n",
        VertexShaderFieldId, VertexShaderFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&PostShaderStage::editHandleVertexShader),
        static_cast<FieldGetMethodSig >(&PostShaderStage::getHandleVertexShader));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "FragmentShader",
        "The shader code to use for the post-process.\n",
        FragmentShaderFieldId, FragmentShaderFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&PostShaderStage::editHandleFragmentShader),
        static_cast<FieldGetMethodSig >(&PostShaderStage::getHandleFragmentShader));

    oType.addInitialDesc(pDesc);
}


PostShaderStageBase::TypeObject PostShaderStageBase::_type(
    PostShaderStageBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&PostShaderStageBase::createEmptyLocal),
    PostShaderStage::initMethod,
    PostShaderStage::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PostShaderStage::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"PostShaderStage\"\n"
    "   parent=\"Stage\"\n"
    "   library=\"EffectGroups\"\n"
    "   pointerfieldtypes=\"none\"\n"
    "   structure=\"concrete\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   useLocalIncludes=\"false\"\n"
    "   isNodeCore=\"true\"\n"
    "   isBundle=\"false\"\n"
    "   docGroupBase=\"GrpEffectsGroupsMisc\"\n"
    "   authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "   >\n"
    "   A stage that uses a shader in a post-process.\n"
    "   <Field\n"
    "       name=\"ColorBufferFormat\"\n"
    "       type=\"GLenum\"\n"
    "       category=\"data\"\n"
    "       cardinality=\"single\"\n"
    "       visibility=\"external\"\n"
    "       defaultValue=\"GL_RGB\"\n"
    "       defaultHeader=\"&quot;OSGGLEXT.h&quot;\"\n"
    "       access=\"public\"\n"
    "       >\n"
    "   </Field>\n"
    "   <Field\n"
    "       name=\"UseColorTextureBuffer\"\n"
    "       type=\"bool\"\n"
    "       category=\"data\"\n"
    "       cardinality=\"single\"\n"
    "       visibility=\"external\"\n"
    "       defaultValue=\"true\"\n"
    "       access=\"public\"\n"
    "       >\n"
    "       Use a texture buffer with the frame buffer object so that the \n"
    "       color buffer is available as a texture in the shader.\n"
    "   </Field>\n"
    "   <Field\n"
    "       name=\"UseDepthTextureBuffer\"\n"
    "       type=\"bool\"\n"
    "       category=\"data\"\n"
    "       cardinality=\"single\"\n"
    "       visibility=\"external\"\n"
    "       defaultValue=\"false\"\n"
    "       access=\"public\"\n"
    "       >\n"
    "       Use a texture buffer with the frame buffer object so that the \n"
    "       depth buffer is available as a texture in the shader.\n"
    "   </Field>\n"
    "   <Field\n"
    "       name=\"VertexShader\"\n"
    "       type=\"std::string\"\n"
    "       category=\"data\"\n"
    "       cardinality=\"single\"\n"
    "       visibility=\"external\"\n"
    "       defaultValue=\"\"\n"
    "       access=\"public\"\n"
    "       >\n"
    "       The shader code to use for the vertex program of the post-process.\n"
    "   </Field>\n"
    "   <Field\n"
    "       name=\"FragmentShader\"\n"
    "       type=\"std::string\"\n"
    "       category=\"data\"\n"
    "       cardinality=\"single\"\n"
    "       visibility=\"external\"\n"
    "       defaultValue=\"\"\n"
    "       access=\"public\"\n"
    "       >\n"
    "       The shader code to use for the post-process.\n"
    "   </Field>\n"
    "</FieldContainer>\n",
    "A stage that uses a shader in a post-process.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PostShaderStageBase::getType(void)
{
    return _type;
}

const FieldContainerType &PostShaderStageBase::getType(void) const
{
    return _type;
}

UInt32 PostShaderStageBase::getContainerSize(void) const
{
    return sizeof(PostShaderStage);
}

/*------------------------- decorator get ------------------------------*/


SFGLenum *PostShaderStageBase::editSFColorBufferFormat(void)
{
    editSField(ColorBufferFormatFieldMask);

    return &_sfColorBufferFormat;
}

const SFGLenum *PostShaderStageBase::getSFColorBufferFormat(void) const
{
    return &_sfColorBufferFormat;
}


SFBool *PostShaderStageBase::editSFUseColorTextureBuffer(void)
{
    editSField(UseColorTextureBufferFieldMask);

    return &_sfUseColorTextureBuffer;
}

const SFBool *PostShaderStageBase::getSFUseColorTextureBuffer(void) const
{
    return &_sfUseColorTextureBuffer;
}


SFBool *PostShaderStageBase::editSFUseDepthTextureBuffer(void)
{
    editSField(UseDepthTextureBufferFieldMask);

    return &_sfUseDepthTextureBuffer;
}

const SFBool *PostShaderStageBase::getSFUseDepthTextureBuffer(void) const
{
    return &_sfUseDepthTextureBuffer;
}


SFString *PostShaderStageBase::editSFVertexShader(void)
{
    editSField(VertexShaderFieldMask);

    return &_sfVertexShader;
}

const SFString *PostShaderStageBase::getSFVertexShader(void) const
{
    return &_sfVertexShader;
}


SFString *PostShaderStageBase::editSFFragmentShader(void)
{
    editSField(FragmentShaderFieldMask);

    return &_sfFragmentShader;
}

const SFString *PostShaderStageBase::getSFFragmentShader(void) const
{
    return &_sfFragmentShader;
}






/*------------------------------ access -----------------------------------*/

UInt32 PostShaderStageBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ColorBufferFormatFieldMask & whichField))
    {
        returnValue += _sfColorBufferFormat.getBinSize();
    }
    if(FieldBits::NoField != (UseColorTextureBufferFieldMask & whichField))
    {
        returnValue += _sfUseColorTextureBuffer.getBinSize();
    }
    if(FieldBits::NoField != (UseDepthTextureBufferFieldMask & whichField))
    {
        returnValue += _sfUseDepthTextureBuffer.getBinSize();
    }
    if(FieldBits::NoField != (VertexShaderFieldMask & whichField))
    {
        returnValue += _sfVertexShader.getBinSize();
    }
    if(FieldBits::NoField != (FragmentShaderFieldMask & whichField))
    {
        returnValue += _sfFragmentShader.getBinSize();
    }

    return returnValue;
}

void PostShaderStageBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ColorBufferFormatFieldMask & whichField))
    {
        _sfColorBufferFormat.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseColorTextureBufferFieldMask & whichField))
    {
        _sfUseColorTextureBuffer.copyToBin(pMem);
    }
    if(FieldBits::NoField != (UseDepthTextureBufferFieldMask & whichField))
    {
        _sfUseDepthTextureBuffer.copyToBin(pMem);
    }
    if(FieldBits::NoField != (VertexShaderFieldMask & whichField))
    {
        _sfVertexShader.copyToBin(pMem);
    }
    if(FieldBits::NoField != (FragmentShaderFieldMask & whichField))
    {
        _sfFragmentShader.copyToBin(pMem);
    }
}

void PostShaderStageBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ColorBufferFormatFieldMask & whichField))
    {
        editSField(ColorBufferFormatFieldMask);
        _sfColorBufferFormat.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseColorTextureBufferFieldMask & whichField))
    {
        editSField(UseColorTextureBufferFieldMask);
        _sfUseColorTextureBuffer.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (UseDepthTextureBufferFieldMask & whichField))
    {
        editSField(UseDepthTextureBufferFieldMask);
        _sfUseDepthTextureBuffer.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (VertexShaderFieldMask & whichField))
    {
        editSField(VertexShaderFieldMask);
        _sfVertexShader.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (FragmentShaderFieldMask & whichField))
    {
        editSField(FragmentShaderFieldMask);
        _sfFragmentShader.copyFromBin(pMem);
    }
}

//! create a new instance of the class
PostShaderStageTransitPtr PostShaderStageBase::createLocal(BitVector bFlags)
{
    PostShaderStageTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PostShaderStage>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PostShaderStageTransitPtr PostShaderStageBase::createDependent(BitVector bFlags)
{
    PostShaderStageTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PostShaderStage>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PostShaderStageTransitPtr PostShaderStageBase::create(void)
{
    PostShaderStageTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PostShaderStage>(tmpPtr);
    }

    return fc;
}

PostShaderStage *PostShaderStageBase::createEmptyLocal(BitVector bFlags)
{
    PostShaderStage *returnValue;

    newPtr<PostShaderStage>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PostShaderStage *PostShaderStageBase::createEmpty(void)
{
    PostShaderStage *returnValue;

    newPtr<PostShaderStage>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr PostShaderStageBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PostShaderStage *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PostShaderStage *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PostShaderStageBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PostShaderStage *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PostShaderStage *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PostShaderStageBase::shallowCopy(void) const
{
    PostShaderStage *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PostShaderStage *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

PostShaderStageBase::PostShaderStageBase(void) :
    Inherited(),
    _sfColorBufferFormat      (GLenum(GL_RGB)),
    _sfUseColorTextureBuffer  (bool(true)),
    _sfUseDepthTextureBuffer  (bool(false)),
    _sfVertexShader           (),
    _sfFragmentShader         ()
{
}

PostShaderStageBase::PostShaderStageBase(const PostShaderStageBase &source) :
    Inherited(source),
    _sfColorBufferFormat      (source._sfColorBufferFormat      ),
    _sfUseColorTextureBuffer  (source._sfUseColorTextureBuffer  ),
    _sfUseDepthTextureBuffer  (source._sfUseDepthTextureBuffer  ),
    _sfVertexShader           (source._sfVertexShader           ),
    _sfFragmentShader         (source._sfFragmentShader         )
{
}


/*-------------------------- destructors ----------------------------------*/

PostShaderStageBase::~PostShaderStageBase(void)
{
}


GetFieldHandlePtr PostShaderStageBase::getHandleColorBufferFormat (void) const
{
    SFGLenum::GetHandlePtr returnValue(
        new  SFGLenum::GetHandle(
             &_sfColorBufferFormat,
             this->getType().getFieldDesc(ColorBufferFormatFieldId),
             const_cast<PostShaderStageBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PostShaderStageBase::editHandleColorBufferFormat(void)
{
    SFGLenum::EditHandlePtr returnValue(
        new  SFGLenum::EditHandle(
             &_sfColorBufferFormat,
             this->getType().getFieldDesc(ColorBufferFormatFieldId),
             this));


    editSField(ColorBufferFormatFieldMask);

    return returnValue;
}

GetFieldHandlePtr PostShaderStageBase::getHandleUseColorTextureBuffer (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfUseColorTextureBuffer,
             this->getType().getFieldDesc(UseColorTextureBufferFieldId),
             const_cast<PostShaderStageBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PostShaderStageBase::editHandleUseColorTextureBuffer(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfUseColorTextureBuffer,
             this->getType().getFieldDesc(UseColorTextureBufferFieldId),
             this));


    editSField(UseColorTextureBufferFieldMask);

    return returnValue;
}

GetFieldHandlePtr PostShaderStageBase::getHandleUseDepthTextureBuffer (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfUseDepthTextureBuffer,
             this->getType().getFieldDesc(UseDepthTextureBufferFieldId),
             const_cast<PostShaderStageBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PostShaderStageBase::editHandleUseDepthTextureBuffer(void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfUseDepthTextureBuffer,
             this->getType().getFieldDesc(UseDepthTextureBufferFieldId),
             this));


    editSField(UseDepthTextureBufferFieldMask);

    return returnValue;
}

GetFieldHandlePtr PostShaderStageBase::getHandleVertexShader    (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfVertexShader,
             this->getType().getFieldDesc(VertexShaderFieldId),
             const_cast<PostShaderStageBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PostShaderStageBase::editHandleVertexShader   (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfVertexShader,
             this->getType().getFieldDesc(VertexShaderFieldId),
             this));


    editSField(VertexShaderFieldMask);

    return returnValue;
}

GetFieldHandlePtr PostShaderStageBase::getHandleFragmentShader  (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfFragmentShader,
             this->getType().getFieldDesc(FragmentShaderFieldId),
             const_cast<PostShaderStageBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr PostShaderStageBase::editHandleFragmentShader (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfFragmentShader,
             this->getType().getFieldDesc(FragmentShaderFieldId),
             this));


    editSField(FragmentShaderFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void PostShaderStageBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PostShaderStage *pThis = static_cast<PostShaderStage *>(this);

    pThis->execSync(static_cast<PostShaderStage *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PostShaderStageBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PostShaderStage *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PostShaderStage *>(pRefAspect),
                  dynamic_cast<const PostShaderStage *>(this));

    return returnValue;
}
#endif

void PostShaderStageBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
