/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSIMPLETEXTFOREGROUNDFIELDS_H_
#define _OSGSIMPLETEXTFOREGROUNDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGUtilDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class SimpleTextForeground;

OSG_GEN_CONTAINERPTR(SimpleTextForeground);

/*! \ingroup GrpUtilFieldTraits
    \ingroup GrpLibOSGUtil
 */
template <>
struct FieldTraits<SimpleTextForeground *> :
    public FieldTraitsFCPtrBase<SimpleTextForeground *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SimpleTextForeground *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_UTIL_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSimpleTextForegroundPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSimpleTextForegroundPtr"; }
};

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSimpleTextForegroundPtr"; 
}

template<> inline
const Char8 *FieldTraits<SimpleTextForeground *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSimpleTextForegroundPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpUtilFieldSFields */
typedef PointerSField<SimpleTextForeground *,
                      RecordedRefCountPolicy  > SFRecSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldSFields */
typedef PointerSField<SimpleTextForeground *,
                      UnrecordedRefCountPolicy> SFUnrecSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldSFields */
typedef PointerSField<SimpleTextForeground *,
                      WeakRefCountPolicy      > SFWeakSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldSFields */
typedef PointerSField<SimpleTextForeground *,
                      NoRefCountPolicy        > SFUncountedSimpleTextForegroundPtr;


/*! \ingroup GrpUtilFieldMFields */
typedef PointerMField<SimpleTextForeground *,
                      RecordedRefCountPolicy  > MFRecSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldMFields */
typedef PointerMField<SimpleTextForeground *,
                      UnrecordedRefCountPolicy> MFUnrecSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldMFields */
typedef PointerMField<SimpleTextForeground *,
                      WeakRefCountPolicy      > MFWeakSimpleTextForegroundPtr;
/*! \ingroup GrpUtilFieldMFields */
typedef PointerMField<SimpleTextForeground *,
                      NoRefCountPolicy        > MFUncountedSimpleTextForegroundPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpUtilFieldSFields \ingroup GrpLibOSGUtil */
struct SFRecSimpleTextForegroundPtr : 
    public PointerSField<SimpleTextForeground *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpUtilFieldSFields \ingroup GrpLibOSGUtil */
struct SFUnrecSimpleTextForegroundPtr : 
    public PointerSField<SimpleTextForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpUtilFieldSFields \ingroup GrpLibOSGUtil */
struct SFWeakSimpleTextForegroundPtr :
    public PointerSField<SimpleTextForeground *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpUtilFieldSFields \ingroup GrpLibOSGUtil */
struct SFUncountedSimpleTextForegroundPtr :
    public PointerSField<SimpleTextForeground *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpUtilFieldMFields \ingroup GrpLibOSGUtil */
struct MFRecSimpleTextForegroundPtr :
    public PointerMField<SimpleTextForeground *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpUtilFieldMFields \ingroup GrpLibOSGUtil */
struct MFUnrecSimpleTextForegroundPtr :
    public PointerMField<SimpleTextForeground *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpUtilFieldMFields \ingroup GrpLibOSGUtil */
struct MFWeakSimpleTextForegroundPtr :
    public PointerMField<SimpleTextForeground *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpUtilFieldMFields \ingroup GrpLibOSGUtil */
struct MFUncountedSimpleTextForegroundPtr :
    public PointerMField<SimpleTextForeground *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSIMPLETEXTFOREGROUNDFIELDS_H_ */
